# name: throw new Exception(...)
# key: exec
# --
throw new Exception("Error Processing Request", 1);